import yfinance as yf
import pandas as pd
import os
cwd = os.getcwd()
AAPL = yf.Ticker("AAPL")
pd.DataFrame(AAPL.info).to_csv("{0}/stocks/AAPL/info.csv".format(cwd))
#pd.DataFrame(AAPL.actions).to_csv("stocks/AAPL/actions.csv")
pd.DataFrame(AAPL.dividends).to_csv("stocks/AAPL/dividends.csv")
pd.DataFrame(AAPL.splits).to_csv("stocks/AAPL/splits.csv")
pd.DataFrame(AAPL.financials).to_csv("stocks/AAPL/financials.csv")
pd.DataFrame(AAPL.quarterly_financials).to_csv("stocks/AAPL/quarterly_financials.csv")
pd.DataFrame(AAPL.major_holders).to_csv("stocks/AAPL/major_holders.csv")
pd.DataFrame(AAPL.institutional_holders).to_csv("stocks/AAPL/institutional_holders.csv")
pd.DataFrame(AAPL.balance_sheet).to_csv("stocks/AAPL/balance_sheet.csv")
pd.DataFrame(AAPL.quarterly_balance_sheet).to_csv("stocks/AAPL/quarterly_balance_sheet.csv")
pd.DataFrame(AAPL.cashflow).to_csv("stocks/AAPL/cashflow.csv")
pd.DataFrame(AAPL.quarterly_cashflow).to_csv("stocks/AAPL/quarterly_cashflow.csv")
pd.DataFrame(AAPL.earnings).to_csv("stocks/AAPL/earnings.csv")
pd.DataFrame(AAPL.quarterly_earnings).to_csv("stocks/AAPL/quarterly_earnings.csv")
pd.DataFrame(AAPL.sustainability).to_csv("stocks/AAPL/sustainability.csv")
pd.DataFrame(AAPL.recommendations).to_csv("stocks/AAPL/recommendations.csv")
pd.DataFrame(AAPL.calendar).to_csv("stocks/AAPL/calendar.csv")
#pd.DataFrame(AAPL.isin).to_csv("stocks/AAPL/isin.csv")
#pd.DataFrame(AAPL.options).to_csv("stocks/AAPL/options.csv")
#pd.DataFrame(AAPL.news).to_csv("stocks/AAPL/news.csv")
